services:

  nodejs-backend:
    image: egorrepnikov/nodejs-backend
    ports:
      - 8081:8080

  postgres:
    image: postgres:16.2
    environment:
      # POSTGRES_USER: user
      # POSTGRES_PASSWORD: password
      # POSTGRES_DATABASE: docker_guide
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
    volumes:
      - ./postgresql/volume/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  reactjs-frontend:
    image: egorrepnikov/reactjs-frontend
    ports:
      - 8080:80
